Fix vitest tests.
The newline at end of commitHash caused this error.

 FAIL  src/__tests__/App.test.tsx [ src/__tests__/App.test.tsx ]
 FAIL  src/__tests__/Authorities.test.tsx [ src/__tests__/Authorities.test.tsx ]
 FAIL  src/__tests__/FSA.test.tsx [ src/__tests__/FSA.test.tsx ]
 FAIL  src/__tests__/Table.test.tsx [ src/__tests__/Table.test.tsx ]
 FAIL  src/__tests__/TableRow.test.tsx [ src/__tests__/TableRow.test.tsx ]
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
 ❯ formatError node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:63765:46
 ❯ TransformContext.error node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:63759:19
 ❯ TransformContext.transform node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:61976:22
 ❯ Object.transform node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:64060:30
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:49741:29